apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: jagyas/service:0.0.91
          ports:
          - containerPort: 3000
          env:
            - name: TARGET
              value: "Go Sample v1"
