apiVersion: v1
kind: Pod
spec:
  serviceAccount: jenkins
  containers:
  - name: shell
    image: alpine
    command:
    - sleep
    args:
      - 30m
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - cat
    tty: true
    volumeMounts:
    - name: kaniko-cache
      mountPath: /cache
    - name: kaniko-secret
      mountPath: /kaniko/.docker/
  - name: knative
    image: gcr.io/knative-releases/knative.dev/client/cmd/kn:latest
    command:
    - sleep
    args:
      - 30m
    tty: true
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json
  - name: kaniko-cache
    persistentVolumeClaim:
      claimName: jenkins-pv-claim
