apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  "labels": {
    "pod" : "kaniko"
  }
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest 
    args: ["--context=git://github.com/jagyas/service",
            "--destination=jagyas/service:0.0.1",
            "--cache=true",
            "--cache-copy-layers",
            "--cache-repo=jagyas/cache",
            "--cache-dir=/cache"]
    volumeMounts:
    - name: kaniko-cache
      mountPath: /cache
    - name: docker-config
      mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
  - name: docker-config
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json
  - name: kaniko-cache
    persistentVolumeClaim:
      claimName: jenkins-pv-claim
